### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by seductorAmadeus** [oAnthocyane/ConsoleApp#1]
1. 
<img width="1482" alt="image" src="https://user-images.githubusercontent.com/18173541/224043511-16d5e30a-28a7-4193-b006-1b50ffcbbc70.png">

**Comment by seductorAmadeus** [comment]
<img width="597" alt="image" src="https://user-images.githubusercontent.com/18173541/224045250-9fdbd8b0-7f3a-45c2-83e8-d73fd3a307dc.png">

**Comment by seductorAmadeus** [comment]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/18173541/224046043-afeef0a7-5d4a-49bf-a92c-5076768b8570.png">

**Comment by oAnthocyane** [comment]
fix this in https://github.com/oAnthocyane/ConsoleApp/commit/30269e723259959d77fb7b23f4f0912d236b197e
